export const VideoData = [
  {
    video: require('../assets/videos/marto1.mp4'),
    postProfile: require('../assets/pps/Jemartob.jpg'),
    title: "Jemartob",
    description: "Marto 1",
    likes: "245k",
    isLike: false,
  },
  {
    video: require('../assets/videos/marto2.mp4'),
    postProfile: require('../assets/pps/Jemartob.jpg'),
    title: "Jemartob",
    description: "Marto 2",
    likes: "600k",
    isLike: false,
  },
  {
    video: require('../assets/videos/marto3.mp4'),
    postProfile: require('../assets/pps/Jemartob.jpg'),
    title: "Jemartob",
    description: "Marto 3",
    likes: "500k",
    isLike: false,
  },
  {
    video: require('../assets/videos/marto4.mp4'),
    postProfile: require('../assets/pps/Jemartob.jpg'),
    title: "Jemartob",
    description: "Marto 4",
    likes: "400k",
    isLike: false,
  },
  {
    video: require('../assets/videos/marto5.mp4'),
    postProfile: require('../assets/pps/Jemartob.jpg'),
    title: "Jemartob",
    description: "Marto 5",
    likes: "300k",
    isLike: false,
  },
  {
    video: require('../assets/videos/marto6.mp4'),
    postProfile: require('../assets/pps/Jemartob.jpg'),
    title: "Jemartob",
    description: "Marto 6",
    likes: "1M",
    isLike: false,
  },
  {
    video: require('../assets/videos/molob1.mp4'),
    postProfile: require('../assets/pps/Jemartob.jpg'),
    title: "Molob",
    description: "Molob 1",
    likes: "2M",
    isLike: false,
  },
  {
    video: require('../assets/videos/molob2.mp4'),
    postProfile: require('../assets/pps/Jemartob.jpg'),
    title: "Molob",
    description: "Molob 2",
    likes: "1.5M",
    isLike: false,
  },
  {
    video: require('../assets/videos/molob3.mp4'),
    postProfile: require('../assets/pps/Jemartob.jpg'),
    title: "Molob",
    description: "Molob 3",
    likes: "4M",
    isLike: false,
  },
  {
    video: require('../assets/videos/molob4.mp4'),
    postProfile: require('../assets/pps/Jemartob.jpg'),
    title: "Molob",
    description: "Molob 4",
    likes: "800k",
    isLike: false,
  },
];
