export const VideoData = [
  {
    video: require("../assets/videos/video1.mp4"),
    postProfile: require("../assets/pps/Jemartob.jpg"),
    title: "Jemartob",
    description: "Marto 1",
    likes: "245k",
    isLike: false,
  },
  {
    video: require("../assets/videos/video2.mp4"),
    postProfile: require("../assets/pps/Jemartob.jpg"),
    title: "Jemartob",
    description: "Marto 2",
    likes: "600k",
    isLike: false,
  },
  {
    video: require("../assets/videos/video3.mp4"),
    postProfile: require("../assets/pps/Jemartob.jpg"),
    title: "Jemartob",
    description: "Marto 3",
    likes: "500k",
    isLike: false,
  },
  {
    video: require("../assets/videos/video4.mp4"),
    postProfile: require("../assets/pps/Jemartob.jpg"),
    title: "Jemartob",
    description: "Marto 4",
    likes: "400k",
    isLike: false,
  },
  {
    video: require("../assets/videos/video5.mp4"),
    postProfile: require("../assets/pps/Jemartob.jpg"),
    title: "Jemartob",
    description: "Marto 5",
    likes: "300k",
    isLike: false,
  },
  {
    video: require("../assets/videos/video6.mp4"),
    postProfile: require("../assets/pps/Jemartob.jpg"),
    title: "Jemartob",
    description: "Marto 6",
    likes: "1M",
    isLike: false,
  },
  {
    video: require("../assets/videos/video7.mp4"),
    postProfile: require("../assets/pps/Molob.jpg"),
    title: "Molob",
    description: "Molob 1",
    likes: "2M",
    isLike: false,
  },
  {
    video: require("../assets/videos/video8.mp4"),
    postProfile: require("../assets/pps/Molob.jpg"),
    title: "Molob",
    description: "Molob 2",
    likes: "1.5M",
    isLike: false,
  },
  {
    video: require("../assets/videos/video9.mp4"),
    postProfile: require("../assets/pps/Molob.jpg"),
    title: "Molob",
    description: "Molob 3",
    likes: "4M",
    isLike: false,
  },
  {
    video: require("../assets/videos/video10.mp4"),
    postProfile: require("../assets/pps/Molob.jpg"),
    title: "Molob",
    description: "Molob 4",
    likes: "800k",
    isLike: false,
  },
];
